### ISSUE TITLE
collections per museums are not being created

### ISSUE THREAD

**Issue by BodhisattwaMandal** [prachatos/museums-of-india#5]
python3 gen_coll_list.py is not giving output.

**Comment by prachatos** [comment]
Is this for 'indices' in museums.ini set to empty?

**Comment by BodhisattwaMandal** [comment]
Both for setting it to empty or adding one index/multiple indices, its not giving any output.

**Comment by prachatos** [comment]
Fixed now. If indices is blank, it will still say 0 collections but works correctly.
